FROM confluentinc/cp-kafka-connect
ADD https://jdbc.postgresql.org/download/postgresql-9.4.1211.jar /etc/kafka-connect/jars/
ADD lib/kafka-connect-ftp-0.1-jar-with-dependencies.jar /etc/kafka-connect/jars/

